name: Run Python Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez un fichier requirements.txt pour vos dépendances.
    - name: Run tests
      run: |
        python <C:\Users\DalilaDerdar\OneDrive - Supplier Assessment Services Limited\Bureau\Scoring_Model\notebook\Streamlit_pages\test_flask.py>
        python <C:\Users\DalilaDerdar\OneDrive - Supplier Assessment Services Limited\Bureau\Scoring_Model\notebook\Streamlit_pages\test_custom.py>
        # ... ajoutez d'autres scripts de test au besoin
