name: Run Python Tests

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        python-version: [3.10.11]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Si vous avez un fichier requirements.txt pour vos dépendances.

    - name: Run test_flask.py
      working-directory: ./notebook/Streamlit_pages
      run: python ./notebook/Streamlit_pages/test_flask.py

    - name: Run test_custom.py
      working-directory: ./notebook/Streamlit_pages
      run: python ./notebook/Streamlit_pages/test_custom.py
